title: "MINGYU PU"
description: "PhD student at NUS | Gaussian Processes · Bayesian Optimization · Video Models"
url: "https://pmy0124nus.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
search: false  # 不需要站内搜索可以关掉

author:
  name: "Mingyu Pu"
  avatar: "/assets/images/pumingyu.png"
  bio: "PhD student at NUS. Interested in Gaussian Process, and Bayesian Optimization."
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=suWFEqgAAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pmy0124nus"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Include index.md so it can render as home
include:
  - index.md
